version: 2.1

jobs:
  build:
    docker:
      - image: cimg/clojure:1.10.1
      - image: mongo:3.6
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
          
      - run: lein test

workflows:
  build:
    jobs:
      - build
